login/urls.py
from django.urls import path, include
from .views import *

app_name = 'login'

urlpatterns = [
    path('',index,name='index'),
    path('login/',login,name='login'),
    path('logout/',logout,name='logout'),
]

story9/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('',include('login.urls', namespace='login')),
    path('admin/', admin.site.urls),
]

login/models.py
from django.db import models

# Create your models here.

login/forms.py
from django import forms
# from django.contrib.auth.forms import UserCreationForm, UserChangeForm
# from .models import Custom_User


class SignUpForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': "form-control",
        'id': "username",
        'placeholder': "Enter username"
    }), min_length=1)
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': "form-control",
        'id': "password",
        'placeholder': "Password"
    }), min_length=8, max_length=32)

login/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login as login_func, logout as logout_func
from .forms import SignUpForm
def index(request):
    return render(request, "landingpage.html")

def login(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login_func(request, user)
            return redirect('/')
        else:
            form = SignUpForm()
            return render(request, 'login.html', {'form': form})
    else:
        form = SignUpForm()
    return render(request, 'login.html', {'form': form})

def logout(request):
    logout_func(request)
    return redirect('/')

login/templates/landingpage.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
    <title>Story 9</title>
  </head>
  <body>
    <div
      class="container vh-100 d-flex justify-content-center align-items-center flex-column"
    >
      {% if user.is_authenticated %}
      <h1>Hi {{ user }}!</h1>
      <a href="{% url 'login:logout' %}">
        <button id="logout">Logout</button>
      </a>
      {% else %}
      <h1>
        Login please.
      </h1>
      <a href="{% url 'login:login' %}">
        <button id="login">Login</button>
      </a>
      {% endif %}
    </div>
    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
      integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

login/templates/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
    <title>Story 9</title>
  </head>
  <body>
    <div
      class="container vh-100 d-flex justify-content-center align-items-center"
    >
      <form action="{% url 'login:login' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
          <label for="username">Username</label>
          {{form.username}}
        </div>
        <div class="form-group">
          <label for="password">Password</label>
          {{form.password}}
        </div>
        <button type="submit" class="btn btn-primary w-100">
          Submit
        </button>
      </form>
    </div>
    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
      integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
      crossorigin="anonymous"
    ></script>
  </body>
</html>